services:
  db:
    image: mysql:8.0
    container_name: npz_db_dev
    env_file: [.env.dev]
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3307:3306"             # доступ к БД с хоста (IDE)
    volumes:
      - db_data_dev:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build:
      context: .
      target: dev
    container_name: npz_api_dev
    depends_on:
      db:
        condition: service_healthy
    env_file: [.env.dev]
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules       # чтобы node_modules были контейнерными
    # healthcheck (если добавили curl в Dockerfile dev):
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/_health >/dev/null || exit 1"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 12

volumes:
  db_data_dev:
